connection_string: "irc.psych0tik.net:6697"
nick: lore
channels:
  - "#lore"
moderated_channels: []
password: "12345"
admins:
  - "ynori7"
use_ssl: true
greetings:
  - "hi"
  - "hello"
  - "sup"
  - "hey"
